### ISSUE TITLE
Wrong port number in example

### ISSUE THREAD

**Issue by LarsNorgaard** [arrogantrabbit/freebsd_storj_installer#1]
Not really that big an issue, but you said the port to 28968, but storj node uses 28967.

I only changed the domain and not the port, when I set it up. Couldn't figure out why it wouldn't connect.

**Comment by arrogantrabbit** [comment]
Thank you for catching it, not sure how it got there. Fixed!

**Comment by arrogantrabbit** [comment]
Fixed in 5e5431a Set port to the example to the actual one storjnode uses by default
