### ISSUE TITLE
improvement : more feedback

### ISSUE THREAD

**Issue by bschwand** [arrogantrabbit/freebsd_storj_installer#4]
Installing in a node that was migrated from an active node (i.e. rsync all the data to new node, stop the node, rsync once more, now install on new node). In that case the data is already a big file hierarchy and the "ownership taking" step, i.e. `chown -R` takes a very long time.
However that is done silently right after installing the dependent packages.
So it looks like the install is stuck on installing unzip or something.

It would be useful to output a message like "taking ownership of database directory..." just before that step is executed.

**Comment by arrogantrabbit** [comment]
Awesome idea, thank you. 

Fixed in bf16617
